apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.6.1
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "CeleryExecutor"
